# Generated by Django 4.2.7 on 2023-12-01 07:53

from django.db import migrations, models
import person.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(null=True, upload_to=person.models.person_image_file_path)),
            ],
        ),
    ]
